### PR TITLE
Tying all components together

### PR DESCRIPTION
**Pull request by MrHardcode**
I had to create some new props and modify some functions here and there to make it all fit together but the application should be ready now. 
Feel free to check out the branch and try it out yourself before approving
- [x] Still needs some cleanup

### CODE REVIEW

**Comment by MrHardcode** [comment]
glue

**Review by Castau — COMMENTED** [review]
It look's good. Is it possible to have the city and country chosen shown in the datepicker? 
This
image

Here somewhere:
image

EDIT. 
And yes, the city-component should be removed if possible
image

**Review by Castau — APPROVED** [review]

**Comment by MrHardcode** [comment]
Okay. Yes, I will remove the city component and its import and I will edit the date picker so it shows the chosen location

**Comment by MrHardcode** [comment]
image
Does this look alright and should the location shown below the map be removed?

**Comment by Castau** [comment]
> Does this look alright and should the location shown below the map be removed?


I looks nice! maybe remove the city from the map but leave the country?

**Review by Castau — APPROVED** [review]

**Comment by MrHardcode** [comment]
Will do

**Pull request merged**
