### PR TITLE
Europe view onclick

### PR DESCRIPTION
**Pull request by MrHardcode**
The map of Europe is now shown and is clickable:
europemap

### CODE REVIEW

**Comment by MrHardcode** [comment]
As you can see in the GIF - the lakes are all clickable. I guess this is a functionality that we don't need and don't want. Should I try to remove the lakes?

**Comment by MalteMagnussen** [comment]
> Should I try to remove the lakes?

Sure, if it isn't too much work. Good work on the map so far.

**Comment by Castau** [comment]
> As you can see in the GIF - the lakes are all clickable. I guess this is a functionality that we don't need and don't want. Should I try to remove the lakes?

Yes i think that would be nice. So if you click on a lake, the country owning the lake is just chosen? And if you click on ocean no country is chosen or something like that?

And gj, it looks nice!

**Comment by MrHardcode** [comment]
I'm trying to find a replacement map that doesn't include lakes because currently all lakes are collected as a single element called "large_masses_of_water". So it is not possible for me to modify the current map other than simply removing all lakes which would force the user to click somewhere on a country where there is no lake (which potentially could cause confusion for some users)

**Comment by MrHardcode** [comment]
Oh snap, nevermind! Check this out: 
europemap2
Problem solved

**Review by Castau — APPROVED** [review]

**Review by Runi-VN — APPROVED** [review]
Nice lake change

**Pull request merged**
